//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 09:18:42 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:grappa:tests:hierarchical:v0.0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.hsh.taskxmleditor.grappa_aspect_hierarchy_v0_0_1;
