//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 09:18:42 AM CET 
//


package de.hsh.taskxmleditor.grappa_aspect_hierarchy_v0_0_1;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for rdkind-type complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="rdkind-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="html" type="{urn:grappa:tests:hierarchical:v0.0.1}repr-html-type"/>
 *           &lt;element name="pdf" type="{urn:grappa:tests:hierarchical:v0.0.1}repr-pdf-type"/>
 *           &lt;element name="plaintext" type="{urn:grappa:tests:hierarchical:v0.0.1}repr-plain-text-type"/>
 *           &lt;element name="none" type="{urn:grappa:tests:hierarchical:v0.0.1}repr-type"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="audience" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rdkind-type", propOrder = {
        "htmlOrPdfOrPlaintext"
})
public class RdkindType {

    @XmlElements({
            @XmlElement(name = "html", type = ReprHtmlType.class),
            @XmlElement(name = "pdf", type = ReprPdfType.class),
            @XmlElement(name = "plaintext", type = ReprPlainTextType.class),
            @XmlElement(name = "none")
    })
    protected ReprType htmlOrPdfOrPlaintext;
    @XmlAttribute(name = "level")
    protected String level;
    @XmlAttribute(name = "audience")
    protected String audience;

    /**
     * Gets the value of the htmlOrPdfOrPlaintext property.
     *
     * @return possible object is
     * {@link ReprHtmlType }
     * {@link ReprPdfType }
     * {@link ReprPlainTextType }
     * {@link ReprType }
     */
    public ReprType getHtmlOrPdfOrPlaintext() {
        return htmlOrPdfOrPlaintext;
    }

    /**
     * Sets the value of the htmlOrPdfOrPlaintext property.
     *
     * @param value allowed object is
     *              {@link ReprHtmlType }
     *              {@link ReprPdfType }
     *              {@link ReprPlainTextType }
     *              {@link ReprType }
     */
    public void setHtmlOrPdfOrPlaintext(ReprType value) {
        this.htmlOrPdfOrPlaintext = value;
    }

    /**
     * Gets the value of the level property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the audience property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAudience() {
        return audience;
    }

    /**
     * Sets the value of the audience property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAudience(String value) {
        this.audience = value;
    }

}
