//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 09:25:16 PM CET 
//


package de.hsh.taskxmleditor.taskxml_v1_1;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for archive-restr-type complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="archive-restr-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="unpack-files-from-archive-regexp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="file-restrictions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element name="required">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{urn:proforma:task:v1.1}mimetype-attr"/>
 *                           &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="optional">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{urn:proforma:task:v1.1}mimetype-attr"/>
 *                           &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attGroup ref="{urn:proforma:task:v1.1}maxsize-attr"/>
 *       &lt;attGroup ref="{urn:proforma:task:v1.1}mimetype-attr"/>
 *       &lt;attGroup ref="{urn:proforma:task:v1.1}archive-attr"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "archive-restr-type", propOrder = {
        "unpackFilesFromArchiveRegexpOrFileRestrictions"
})
public class ArchiveRestrType {

    @XmlElements({
            @XmlElement(name = "unpack-files-from-archive-regexp", type = String.class),
            @XmlElement(name = "file-restrictions", type = ArchiveRestrType.FileRestrictions.class)
    })
    protected Object unpackFilesFromArchiveRegexpOrFileRestrictions;
    @XmlAttribute(name = "max-size")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxSize;
    @XmlAttribute(name = "mime-type-regexp")
    protected String mimeTypeRegexp;
    @XmlAttribute(name = "allowed-archive-filename-regexp")
    protected String allowedArchiveFilenameRegexp;

    /**
     * Gets the value of the unpackFilesFromArchiveRegexpOrFileRestrictions property.
     *
     * @return possible object is
     * {@link String }
     * {@link ArchiveRestrType.FileRestrictions }
     */
    public Object getUnpackFilesFromArchiveRegexpOrFileRestrictions() {
        return unpackFilesFromArchiveRegexpOrFileRestrictions;
    }

    /**
     * Sets the value of the unpackFilesFromArchiveRegexpOrFileRestrictions property.
     *
     * @param value allowed object is
     *              {@link String }
     *              {@link ArchiveRestrType.FileRestrictions }
     */
    public void setUnpackFilesFromArchiveRegexpOrFileRestrictions(Object value) {
        this.unpackFilesFromArchiveRegexpOrFileRestrictions = value;
    }

    /**
     * Gets the value of the maxSize property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getMaxSize() {
        return maxSize;
    }

    /**
     * Sets the value of the maxSize property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setMaxSize(BigInteger value) {
        this.maxSize = value;
    }

    /**
     * Gets the value of the mimeTypeRegexp property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMimeTypeRegexp() {
        return mimeTypeRegexp;
    }

    /**
     * Sets the value of the mimeTypeRegexp property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMimeTypeRegexp(String value) {
        this.mimeTypeRegexp = value;
    }

    /**
     * Gets the value of the allowedArchiveFilenameRegexp property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAllowedArchiveFilenameRegexp() {
        return allowedArchiveFilenameRegexp;
    }

    /**
     * Sets the value of the allowedArchiveFilenameRegexp property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAllowedArchiveFilenameRegexp(String value) {
        this.allowedArchiveFilenameRegexp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="required">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{urn:proforma:task:v1.1}mimetype-attr"/>
     *                 &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="optional">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{urn:proforma:task:v1.1}mimetype-attr"/>
     *                 &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "requiredOrOptional"
    })
    public static class FileRestrictions {

        @XmlElements({
                @XmlElement(name = "required", type = ArchiveRestrType.FileRestrictions.Required.class),
                @XmlElement(name = "optional", type = ArchiveRestrType.FileRestrictions.Optional.class)
        })
        protected List<Object> requiredOrOptional;

        /**
         * Gets the value of the requiredOrOptional property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the requiredOrOptional property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRequiredOrOptional().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ArchiveRestrType.FileRestrictions.Required }
         * {@link ArchiveRestrType.FileRestrictions.Optional }
         */
        public List<Object> getRequiredOrOptional() {
            if (requiredOrOptional == null) {
                requiredOrOptional = new ArrayList<Object>();
            }
            return this.requiredOrOptional;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{urn:proforma:task:v1.1}mimetype-attr"/>
         *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Optional {

            @XmlAttribute(name = "path", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String path;
            @XmlAttribute(name = "mime-type-regexp")
            protected String mimeTypeRegexp;

            /**
             * Gets the value of the path property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getPath() {
                return path;
            }

            /**
             * Sets the value of the path property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setPath(String value) {
                this.path = value;
            }

            /**
             * Gets the value of the mimeTypeRegexp property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getMimeTypeRegexp() {
                return mimeTypeRegexp;
            }

            /**
             * Sets the value of the mimeTypeRegexp property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setMimeTypeRegexp(String value) {
                this.mimeTypeRegexp = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{urn:proforma:task:v1.1}mimetype-attr"/>
         *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Required {

            @XmlAttribute(name = "path", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String path;
            @XmlAttribute(name = "mime-type-regexp")
            protected String mimeTypeRegexp;

            /**
             * Gets the value of the path property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getPath() {
                return path;
            }

            /**
             * Sets the value of the path property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setPath(String value) {
                this.path = value;
            }

            /**
             * Gets the value of the mimeTypeRegexp property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getMimeTypeRegexp() {
                return mimeTypeRegexp;
            }

            /**
             * Sets the value of the mimeTypeRegexp property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setMimeTypeRegexp(String value) {
                this.mimeTypeRegexp = value;
            }

        }

    }

}
