//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 09:25:16 PM CET 
//


package de.hsh.taskxmleditor.taskxml_v1_1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the de.hsh.taskxmleditor.xml.taskxml package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.hsh.taskxmleditor.xml.taskxml
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArchiveRestrType }
     */
    public ArchiveRestrType createArchiveRestrType() {
        return new ArchiveRestrType();
    }

    /**
     * Create an instance of {@link ArchiveRestrType.FileRestrictions }
     */
    public ArchiveRestrType.FileRestrictions createArchiveRestrTypeFileRestrictions() {
        return new ArchiveRestrType.FileRestrictions();
    }

    /**
     * Create an instance of {@link FileRestrType }
     */
    public FileRestrType createFileRestrType() {
        return new FileRestrType();
    }

    /**
     * Create an instance of {@link Task }
     */
    public Task createTask() {
        return new Task();
    }

    /**
     * Create an instance of {@link Proglang }
     */
    public Proglang createProglang() {
        return new Proglang();
    }

    /**
     * Create an instance of {@link SubmissionRestrictions }
     */
    public SubmissionRestrictions createSubmissionRestrictions() {
        return new SubmissionRestrictions();
    }

    /**
     * Create an instance of {@link Files }
     */
    public Files createFiles() {
        return new Files();
    }

    /**
     * Create an instance of {@link ExternalResources }
     */
    public ExternalResources createExternalResources() {
        return new ExternalResources();
    }

    /**
     * Create an instance of {@link ModelSolutions }
     */
    public ModelSolutions createModelSolutions() {
        return new ModelSolutions();
    }

    /**
     * Create an instance of {@link Tests }
     */
    public Tests createTests() {
        return new Tests();
    }

    /**
     * Create an instance of {@link GradingHints }
     */
    public GradingHints createGradingHints() {
        return new GradingHints();
    }

    /**
     * Create an instance of {@link MetaData }
     */
    public MetaData createMetaData() {
        return new MetaData();
    }

    /**
     * Create an instance of {@link Test }
     */
    public Test createTest() {
        return new Test();
    }

    /**
     * Create an instance of {@link ExternalResource }
     */
    public ExternalResource createExternalResource() {
        return new ExternalResource();
    }

    /**
     * Create an instance of {@link Filerefs }
     */
    public Filerefs createFilerefs() {
        return new Filerefs();
    }

    /**
     * Create an instance of {@link ModelSolution }
     */
    public ModelSolution createModelSolution() {
        return new ModelSolution();
    }

    /**
     * Create an instance of {@link File }
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link TestMetaData }
     */
    public TestMetaData createTestMetaData() {
        return new TestMetaData();
    }

    /**
     * Create an instance of {@link Externalresourceref }
     */
    public Externalresourceref createExternalresourceref() {
        return new Externalresourceref();
    }

    /**
     * Create an instance of {@link TestConfiguration }
     */
    public TestConfiguration createTestConfiguration() {
        return new TestConfiguration();
    }

    /**
     * Create an instance of {@link FileRegexpRestrType }
     */
    public FileRegexpRestrType createFileRegexpRestrType() {
        return new FileRegexpRestrType();
    }

    /**
     * Create an instance of {@link Fileref }
     */
    public Fileref createFileref() {
        return new Fileref();
    }

    /**
     * Create an instance of {@link Externalresourcerefs }
     */
    public Externalresourcerefs createExternalresourcerefs() {
        return new Externalresourcerefs();
    }

    /**
     * Create an instance of {@link ArchiveRestrType.FileRestrictions.Required }
     */
    public ArchiveRestrType.FileRestrictions.Required createArchiveRestrTypeFileRestrictionsRequired() {
        return new ArchiveRestrType.FileRestrictions.Required();
    }

    /**
     * Create an instance of {@link ArchiveRestrType.FileRestrictions.Optional }
     */
    public ArchiveRestrType.FileRestrictions.Optional createArchiveRestrTypeFileRestrictionsOptional() {
        return new ArchiveRestrType.FileRestrictions.Optional();
    }

    /**
     * Create an instance of {@link FileRestrType.Required }
     */
    public FileRestrType.Required createFileRestrTypeRequired() {
        return new FileRestrType.Required();
    }

    /**
     * Create an instance of {@link FileRestrType.Optional }
     */
    public FileRestrType.Optional createFileRestrTypeOptional() {
        return new FileRestrType.Optional();
    }

}
