//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.02.21 at 09:25:16 PM CET
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:proforma:task:v1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.hsh.taskxmleditor.taskxml_v1_1;
