//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 09:25:16 PM CET 
//

package de.hsh.taskxmleditor.taskxml_v1_1;

import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for submission-restrictions complex type.
 * <p>
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * <pre>
 * &lt;complexType name="submission-restrictions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="archive-restriction" type="{urn:proforma:task:v1.1}archive-restr-type"/>
 *         &lt;element name="files-restriction" type="{urn:proforma:task:v1.1}file-restr-type"/>
 *         &lt;element name="regexp-restriction" type="{urn:proforma:task:v1.1}file-regexp-restr-type"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "submission-restrictions", propOrder = {"restrictionObject"})
public class SubmissionRestrictions {

    @XmlElements({@XmlElement(name = "archive-restriction", type = ArchiveRestrType.class),
            @XmlElement(name = "files-restriction", type = FileRestrType.class),
            @XmlElement(name = "regexp-restriction", type = FileRegexpRestrType.class)})
    protected Object restrictionObject;

    /**
     * Gets the value of the restrictionObject property.
     *
     * @return possible object is {@link ArchiveRestrType } {@link FileRestrType
     * } {@link FileRegexpRestrType }
     */
    public Object getRestrictionObject() {
        return restrictionObject;
    }

    /**
     * Sets the value of the restrictionObject property.
     *
     * @param value allowed object is {@link ArchiveRestrType }
     *              {@link FileRestrType } {@link FileRegexpRestrType }
     */
    public void setRestrictionObject(Object value) {
        this.restrictionObject = value;
    }

}
