//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 09:25:16 PM CET 
//

package de.hsh.taskxmleditor.taskxml_v1_1;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;

/**
 * <p>
 * Java class for test complex type.
 * <p>
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * <pre>
 * &lt;complexType name="test">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{urn:proforma:task:v1.1}title"/>
 *         &lt;element name="test-type" type="{urn:proforma:task:v1.1}test-type"/>
 *         &lt;element name="test-configuration" type="{urn:proforma:task:v1.1}test-configuration"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="validity" default="1.00">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;totalDigits value="3"/>
 *             &lt;fractionDigits value="2"/>
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="1.00"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "test", propOrder = {"title", "testType", "testConfiguration"})
public class Test {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(name = "test-type", required = true)
    protected String testType;
    @XmlElement(name = "test-configuration", required = true)
    protected TestConfiguration testConfiguration;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "validity")
    protected BigDecimal validity;

    /**
     * Gets the value of the title property.
     *
     * @return possible object is {@link String }
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value allowed object is {@link String }
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the testType property.
     *
     * @return possible object is {@link String }
     */
    public String getTestType() {
        return testType;
    }

    /**
     * Sets the value of the testType property.
     *
     * @param value allowed object is {@link String }
     */
    public void setTestType(String value) {
        this.testType = value;
    }

    /**
     * Gets the value of the testConfiguration property.
     *
     * @return possible object is {@link TestConfiguration }
     */
    public TestConfiguration getTestConfiguration() {
        return testConfiguration;
    }

    /**
     * Sets the value of the testConfiguration property.
     *
     * @param value allowed object is {@link TestConfiguration }
     */
    public void setTestConfiguration(TestConfiguration value) {
        this.testConfiguration = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the validity property.
     *
     * @return possible object is {@link BigDecimal }
     */
    public BigDecimal getValidity() {
        if (validity == null) {
            return new BigDecimal("1.00");
        } else {
            return validity;
        }
    }

    /**
     * Sets the value of the validity property.
     *
     * @param value allowed object is {@link BigDecimal }
     */
    public void setValidity(BigDecimal value) {
        this.validity = value;
    }

    @Override
    public String toString() {
        return String.format("%s (%s)", getId(), getTitle());
    }
}
